//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wod
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<int> tipoConteo { get; set; }
        public int idTenant { get; set; }
    
        public virtual nivel nivel1 { get; set; }
        public virtual tenant tenant { get; set; }
        public virtual tipoConteo tipoConteo1 { get; set; }
    }
}
